name: restop

on: [push]

jobs:
    build-linux-musl:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Config
              id: config
              run: |
                  echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
                  echo ::set-output name=TARGET_NAME::x86_64-unknown-linux-musl
            - uses: actions/checkout@master
            - name: Build
              uses: stevenleadbeater/rust-musl-builder@master
              with:
                  args: /bin/bash -c "export DESTINY_API_KEY=${{ secrets.DESTINY_API_KEY }} && rustup toolchain install 1.65.0 && rustup target add x86_64-unknown-linux-musl --toolchain=1.65.0 && rustup override set 1.65.0 && cargo build --manifest-path=src/Cargo.toml --release --target=x86_64-unknown-linux-musl"
            - name: Process and Package
              if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
              env:
                  SOURCE_TAG: ${{ steps.config.outputs.SOURCE_TAG }}
                  TARGET_NAME: ${{ steps.config.outputs.TARGET_NAME }}
              run: echo SOURCE_TAG ${SOURCE_TAG} && echo TARGET_NAME ${TARGET_NAME} && ls -l src/target/ && cp src/target/${TARGET_NAME}/release/restop . && zip -j restop_${TARGET_NAME}_${SOURCE_TAG}.zip restop

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      restop_${{ steps.config.outputs.TARGET_NAME }}_${{ steps.config.outputs.SOURCE_TAG }}.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
